FROM python:3.10-slim

RUN pip install --no-cache-dir mlflow==2.10.0 boto3==1.34.34

WORKDIR /mlflow

EXPOSE 5000

CMD ["mlflow", "server", \
     "--host", "0.0.0.0", \
     "--port", "5000", \
     "--backend-store-uri", "/mlflow/mlruns", \
     "--default-artifact-root", "${MLFLOW_ARTIFACT_ROOT}"]
