apiVersion: v1
kind: ResourceQuota
metadata:
  name: fraud-a4-quota
  namespace: fraud-a4
spec:
  hard:
    requests.cpu: "6"
    requests.memory: 6Gi
    limits.cpu: "8"
    limits.memory: 8Gi
    pods: "20"
    persistentvolumeclaims: "5"
